language: node_js
node_js:
  - '12.4'
cache: npm
env:
  - LOGIN=$LOGIN
  - PASSWORD=$PASSWORD
  - GATSBY_FIREBASE_API_KEY=$GATSBY_FIREBASE_API_KEY
  - GATSBY_FIREBASE_AUTH_DOMAIN=$GATSBY_FIREBASE_AUTH_DOMAIN
  - GATSBY_FIREBASE_DATABASE_URL=$GATSBY_FIREBASE_DATABASE_URL
  - GATSBY_FIREBASE_PROJECT_ID=$GATSBY_FIREBASE_PROJECT_ID
  - GATSBY_FIREBASE_STORAGE_BUCKET=$GATSBY_FIREBASE_STORAGE_BUCKET
  - GATSBY_FIREBASE_MESSAGING_SENDER_ID=$GATSBY_FIREBASE_MESSAGING_SENDER_ID
  - GATSBY_FIREBASE_APP_ID=$GATSBY_FIREBASE_APP_ID
  - GATSBY_FIREBASE_MEASUREMENT_ID=$GATSBY_FIREBASE_MEASUREMENT_ID
  - GA_TRACKING_ID=$GA_TRACKING_ID
install:
  - npm install -g firebase-tools
  - npm install -g gatsby
  - npm install
  - cd functions
  - npm install
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
branches:
  only:
    - master
